//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public System.DateTime Time { get; set; }
        public decimal MaxNumberOfParticipants { get; set; }
        public decimal NumberOfFreePlaces { get; set; }
    }
}
